### ISSUE TITLE
Custom name for user table

### ISSUE THREAD

**Issue by nstojanovickg** [SCIF/propel-laravel#2]
Hi, I use your Auth propel driver and I like it.
But I have small problem, my auth user table is not named with 'user'. It seams to be the name of user table is hard coded in PropelUserProvider. 
It would be great if we can use custom name for 'user' table.

I found a way that you can easily fix this, just add: 
$table = \Config::get('auth.table'); in retrieveByCredentials 
and instead of using 'User', use $table.

I'm sorry if there is already a way to use of another name for 'user' table.

**Comment by SCIF** [comment]
Hi @nstojanovickg !

Just edit your schema.xml like this:

```
<table name="some_custom_users_tablename" idMethod="native" phpName="User">
```

And it will create model User mapped to custom table.

**Comment by nstojanovickg** [comment]
Actually it's kind of hard coding. And there are several problems:
- I can not have another table called 'user' , or need to change phpName, and so on...
- 'xxxx_user' table  (or any other table name) need to call with mismatched name User, so if at any other place I want to call this table I need to call with wrong name (and need to change if already use anywhere else).
- Also, if I accept this way, when I change my database and rebuild schema I need to change manually phpName every time.

**Comment by SCIF** [comment]
I just didn't figure out what you ask. Now it's clear.

It's not table — it's name of model. It configures in config as `auth.model` value. You are correct that now it hardcoded. I will fix it in few mins. Thanks!

**Comment by nstojanovickg** [comment]
Great, thanks.
