### ISSUE TITLE
php artisan route:list  command doesn't work

### ISSUE THREAD

**Issue by nstojanovickg** [SCIF/propel-laravel#3]
When I run 'php artisan route:list' command it show an error 'Driver [propel] not supported.'.
I notice in RuntimeServiceProvider your comment: 'skip auth driver adding if running as CLI to avoid auth model not found'. 
But is this necessary? When I remove '! \App::runningInConsole()' from if condition, route:list command pass correctly.

**Comment by SCIF** [comment]
I really don't know why, but when i did that — it made sense.  Will inspect it again. May be laravel implementation modified and some things works ok which brakes everything ealier.

**Comment by SCIF** [comment]
Remembered! It's [chicken and egg dilema](https://github.com/SCIF/propel-laravel/commit/7f25bfa79c9e2b50f9d0cdc35f655c48a78b533e#diff-04215757fb37b6a302fb8f7a2790fde1R88). You need to run `model:build` to create User model but you can't because task can't start because User model not found and Auth provider can't be registered. WIll find workaround, if currently it not solved truly.

**Comment by nstojanovickg** [comment]
Great, thanks a lot.

**Comment by nstojanovickg** [comment]
I'm sorry, but now works only for command line, and for the website does not.
ErrorException in ArgvInput.php line 57:
Undefined index: argv

**Comment by nstojanovickg** [comment]
I hope you do not mind if I suggest:
if(\App::runningInConsole()){
            $input = new ArgvInput();
            if ('propel:model:build' == $input->getFirstArgument()){
                return;
            }
        }

```
    // skip auth driver adding if running as CLI to avoid auth model not found
    if ('propel' === \Config::get('auth.driver')) {
```

...
} 
This is my temporary solution till you publish correct one.

**Comment by SCIF** [comment]
Fixed again :) @nstojanovickg test it please. Thanks for your reports!

**Comment by SCIF** [comment]
I didn't detect that issue, because my own installation works ok with previous version of fix. It's because i use hhvm and it creates empty array in `$_SERVER['argv']`  :open_mouth:

**Comment by nstojanovickg** [comment]
No problem, now it's all right. Thanks a lot.
