### ISSUE TITLE
Library no more developing?

### ISSUE THREAD

**Issue by dimaxz** [SCIF/propel-laravel#7]
the actual question in the title

**Comment by SCIF** [comment]
@dimaxz , hey!

This repo is abandoned and the most current version of adapter you can find in [official repo](https://github.com/propelorm/PropelLaravel) (the dev branch is quite stable afaik and contain a lot of changes, consult [upgrade doc](https://github.com/propelorm/PropelLaravel/blob/develop/docs/upgrade.md)). I had to mark it as abandoned but didn't still.
